# Clave privada generada por Terraform
[webapp]
webserver ansible_host=20.188.56.126 ansible_user=azureuser ansible_ssh_private_key_file=ssh_key.pem ansible_python_interpreter=/usr/bin/python3

[acr]
localhost ansible_connection=local

[aks]
localhost ansible_connection=local

[all:vars]
# Variables globales del proyecto
resource_group_name=UNIR-casopractico2
aks_name=aks-casopractico2
acr_name=jevdevopscp2
acr_login_server=jevdevopscp2.azurecr.io
vm_public_ip=20.188.56.126
container_image_tag=casopractico2
web_image_name=nginx-web
app_frontend_image_name=azure-vote-front
app_backend_image_name=redis
app_namespace=casopractico2